// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as codex$0 from "./internal/codex/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(257367811);
}

export function ApplyProviderRouterToCodex(): $CancellablePromise<$models.ProviderRouterView> {
    return $Call.ByID(231535978);
}

export function ApplyUpdateAndRestart(): $CancellablePromise<void> {
    return $Call.ByID(3133742711);
}

export function ArchiveClaudeSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(890897534, sessionID);
}

/**
 * ArchiveGrokSession hides a session from the main list (local archive index).
 */
export function ArchiveGrokSession(backend: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(785972473, backend, sessionID);
}

export function ArchiveThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(404527456, threadID);
}

/**
 * AttachImageData saves a pasted/dropped image into NiceCodex-managed persistent
 * attachment storage and registers it for SendMessage (same allow-list as SelectImages).
 */
export function AttachImageData(fileName: string, mimeType: string, dataBase64: string): $CancellablePromise<string> {
    return $Call.ByID(3374776048, fileName, mimeType, dataBase64);
}

export function Bootstrap(): $CancellablePromise<$models.BootstrapData> {
    return $Call.ByID(4177956144);
}

export function BrowserBack(): $CancellablePromise<void> {
    return $Call.ByID(193132621);
}

export function BrowserForward(): $CancellablePromise<void> {
    return $Call.ByID(1722237139);
}

export function BrowserReload(): $CancellablePromise<void> {
    return $Call.ByID(2544793859);
}

export function CancelUpdateDownload(): $CancellablePromise<void> {
    return $Call.ByID(1670800741);
}

/**
 * CheckCLITools detects every supported local CLI and queries npm for latest versions.
 */
export function CheckCLITools(): $CancellablePromise<$models.CLIToolsReport> {
    return $Call.ByID(4153243591);
}

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(3671876993);
}

export function CheckProviderConfiguration(providerID: string, force: boolean): $CancellablePromise<$models.ProviderConfigurationView> {
    return $Call.ByID(1084288519, providerID, force);
}

/**
 * ClearGrokMemory wipes Grok's persisted memory (`grok memory clear`).
 */
export function ClearGrokMemory(): $CancellablePromise<void> {
    return $Call.ByID(2633097791);
}

export function CodexStatus(): $CancellablePromise<codex$0.Status> {
    return $Call.ByID(3760924599);
}

export function CommitGitChanges(request: $models.GitCommitRequest): $CancellablePromise<$models.GitActionResult> {
    return $Call.ByID(3986674178, request);
}

export function CompactClaudeSession(sessionID: string): $CancellablePromise<$models.ClaudeCompactionResult> {
    return $Call.ByID(1104019359, sessionID);
}

export function CompactThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(2159280559, threadID);
}

export function CreateGitBranch(request: $models.GitBranchRequest): $CancellablePromise<$models.GitActionResult> {
    return $Call.ByID(376396278, request);
}

/**
 * CreateRuntimeThread allocates a lazy local session for one arena pane without
 * relying on the globally focused runtime changing while another pane is sending.
 */
export function CreateRuntimeThread(runtimeID: string, workspace: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1507699650, runtimeID, workspace);
}

export function CreateThread(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1065248874);
}

export function DeleteClaudeSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3047900465, sessionID);
}

export function DeleteGrokSession(backend: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2818978826, backend, sessionID);
}

export function DeleteMCPServer(name: string): $CancellablePromise<void> {
    return $Call.ByID(1611204592, name);
}

export function DeleteScheduledTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3352537869, id);
}

export function DeleteThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(1472565121, threadID);
}

export function DownloadAndStageUpdate(): $CancellablePromise<$models.UpdateProgress> {
    return $Call.ByID(3358895366);
}

export function FocusBrowser(): $CancellablePromise<void> {
    return $Call.ByID(1719904498);
}

export function ForkThread(threadID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1034771762, threadID);
}

export function GetGitHubIssueImportContext(workspace: string): $CancellablePromise<$models.GitHubIssueImportContext> {
    return $Call.ByID(3179848564, workspace);
}

export function ImportGitHubIssue(workspace: string, reference: string): $CancellablePromise<$models.GitHubIssueContent> {
    return $Call.ByID(3703804695, workspace, reference);
}

export function ImportMCPServers(request: $models.MCPServersImportRequest): $CancellablePromise<void> {
    return $Call.ByID(340745843, request);
}

/**
 * InstallCLITool installs or upgrades a CLI.
 * Codex / Claude / Gemini / OpenCode use pnpm global packages.
 * Grok Build uses the official x.ai installer / `grok update` (native binary).
 */
export function InstallCLITool(toolID: string): $CancellablePromise<$models.CLIToolActionResult> {
    return $Call.ByID(1201058047, toolID);
}

export function InstallPlugin(request: $models.PluginInstallRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3003226110, request);
}

export function InterruptClaudeTurn(ref: $models.ClaudeTurnRef): $CancellablePromise<void> {
    return $Call.ByID(2866027964, ref);
}

export function InterruptGrokTurn(ref: $models.GrokTurnRef): $CancellablePromise<void> {
    return $Call.ByID(1498414485, ref);
}

export function InterruptTurn(threadID: string, turnID: string): $CancellablePromise<void> {
    return $Call.ByID(935266466, threadID, turnID);
}

export function IsClaudeTurnRunning(ref: $models.ClaudeTurnRef): $CancellablePromise<boolean> {
    return $Call.ByID(2635517826, ref);
}

export function IsGrokTurnRunning(ref: $models.GrokTurnRef): $CancellablePromise<boolean> {
    return $Call.ByID(625464937, ref);
}

export function ListApps(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2844972250);
}

export function ListArchivedClaudeSessions(): $CancellablePromise<$models.ClaudeSessionSummary[] | null> {
    return $Call.ByID(376361943);
}

/**
 * ListArchivedGrokSessions returns NiceCodex-local archived Grok sessions.
 */
export function ListArchivedGrokSessions(backend: string, search: string): $CancellablePromise<$models.GrokSessionSummary[] | null> {
    return $Call.ByID(2504986910, backend, search);
}

export function ListArchivedThreads(search: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(795343881, search);
}

/**
 * ListClaudeSessionTurnUsages restores the most recent request context after
 * reopening a native Claude Code transcript.
 */
export function ListClaudeSessionTurnUsages(sessionID: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(1618295575, sessionID);
}

export function ListClaudeSessions(workspace: string, search: string): $CancellablePromise<$models.ClaudeSessionSummary[] | null> {
    return $Call.ByID(4114062377, workspace, search);
}

export function ListCollaborationModes(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2846685189);
}

export function ListExperimentalFeatures(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(626848283);
}

export function ListGitBranches(workspace: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1470002806, workspace);
}

/**
 * ListGrokSessionTurnUsages returns per-turn token breakdown for one Grok session
 * (from updates.jsonl turn_completed). Used to populate the chat message footer.
 */
export function ListGrokSessionTurnUsages(sessionID: string): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(3387849376, sessionID);
}

export function ListGrokSessions(backend: string, workspace: string, search: string): $CancellablePromise<$models.GrokSessionSummary[] | null> {
    return $Call.ByID(1741024260, backend, workspace, search);
}

export function ListHooks(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2720002358);
}

export function ListLocalMemories(): $CancellablePromise<$models.MemoriesOverview> {
    return $Call.ByID(1204786654);
}

export function ListMCPServerStatus(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2306388879);
}

export function ListMCPServers(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1027663362);
}

export function ListModelProviders(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2342522979);
}

export function ListModels(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4263467744);
}

export function ListPlugins(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(442045366);
}

export function ListRuntimeWorkspaceThreads(runtimeID: string, workspace: string, search: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(775825556, runtimeID, workspace, search);
}

export function ListScheduledTasks(): $CancellablePromise<$models.ScheduledTask[] | null> {
    return $Call.ByID(2711200733);
}

export function ListSkills(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3162367268);
}

export function ListSystemFonts(): $CancellablePromise<$models.SystemFont[] | null> {
    return $Call.ByID(1974567495);
}

export function ListThreads(search: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3185449219, search);
}

export function ListWorkspaceThreads(workspace: string, search: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2536997788, workspace, search);
}

export function LogoutAccount(): $CancellablePromise<void> {
    return $Call.ByID(2683059787);
}

export function OpenBrowser(rawURL: string): $CancellablePromise<string> {
    return $Call.ByID(3692280918, rawURL);
}

export function OpenBrowserDevTools(): $CancellablePromise<void> {
    return $Call.ByID(1516554564);
}

/**
 * OpenBrowserDownloadDir reveals the configured download folder in the OS file manager.
 */
export function OpenBrowserDownloadDir(): $CancellablePromise<void> {
    return $Call.ByID(4097011765);
}

export function OpenClaudeConfigFile(): $CancellablePromise<void> {
    return $Call.ByID(3636053624);
}

export function OpenClaudeHome(): $CancellablePromise<void> {
    return $Call.ByID(3858670087);
}

export function OpenExternal(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(2121391737, rawURL);
}

export function OpenGrokConfigFile(): $CancellablePromise<void> {
    return $Call.ByID(3862982997);
}

export function OpenGrokHome(): $CancellablePromise<void> {
    return $Call.ByID(2792450522);
}

/**
 * OpenLocalPath opens a workspace-local file or folder with the OS default handler.
 * Accepts absolute paths, workspace-relative paths, and file:// URLs.
 */
export function OpenLocalPath(rawPath: string): $CancellablePromise<void> {
    return $Call.ByID(2064324498, rawPath);
}

export function OpenMemoriesFolder(): $CancellablePromise<void> {
    return $Call.ByID(2340956881);
}

export function OpenTerminal(): $CancellablePromise<void> {
    return $Call.ByID(3614603658);
}

/**
 * OpenWorkspaceLocalPath keeps file links in a background arena pane scoped to
 * that conversation's project instead of the globally focused runtime folder.
 */
export function OpenWorkspaceLocalPath(rawPath: string, workspace: string): $CancellablePromise<void> {
    return $Call.ByID(1396600385, rawPath, workspace);
}

/**
 * PreviewImage returns a data-URL for an allow-listed attachment so the UI can show thumbnails.
 */
export function PreviewImage(path: string): $CancellablePromise<string> {
    return $Call.ByID(2624332779, path);
}

export function PushGitBranch(): $CancellablePromise<$models.GitActionResult> {
    return $Call.ByID(2060389666);
}

export function ReadAccount(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3417819837);
}

export function ReadAccountRateLimits(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3284885595);
}

/**
 * ReadAccountUsage returns spend for the active runtime only.
 * Codex may backfill from ~/.codex rollouts / ChatGPT cloud when its local bucket is empty.
 * Grok backfills input/output/cache/reasoning from ~/.grok session updates.jsonl when missing.
 * Claude backfills from ~/.claude/projects/** /*.jsonl assistant message.usage when missing.
 */
export function ReadAccountUsage(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3812997328);
}

export function ReadClaudeCapabilities(): $CancellablePromise<$models.ClaudeCapabilitiesCatalog> {
    return $Call.ByID(3255146774);
}

export function ReadClaudeGlobalInstructions(): $CancellablePromise<$models.GlobalInstructionsInfo> {
    return $Call.ByID(2905891186);
}

export function ReadClaudeProjectInstructions(): $CancellablePromise<$models.ProjectInstructionsInfo> {
    return $Call.ByID(1543098932);
}

export function ReadClaudeSession(sessionID: string): $CancellablePromise<$models.ClaudeSessionDetail> {
    return $Call.ByID(392135644, sessionID);
}

export function ReadClaudeSessionHistory(sessionID: string, before: number): $CancellablePromise<$models.ClaudeSessionDetail> {
    return $Call.ByID(325508716, sessionID, before);
}

export function ReadClaudeTurnLiveness(ref: $models.ClaudeTurnRef): $CancellablePromise<$models.TurnLivenessView> {
    return $Call.ByID(2190616074, ref);
}

export function ReadCodexFeatureFlags(): $CancellablePromise<$models.CodexFeatureFlags> {
    return $Call.ByID(1079251556);
}

export function ReadExternalRuntimeCatalog(runtime: string, workspace: string): $CancellablePromise<$models.ExternalRuntimeCatalog> {
    return $Call.ByID(2982606466, runtime, workspace);
}

/**
 * ReadGlobalInstructions returns personal Codex AGENTS.md content from disk.
 */
export function ReadGlobalInstructions(): $CancellablePromise<$models.GlobalInstructionsInfo> {
    return $Call.ByID(2724052924);
}

export function ReadGrokCapabilities(): $CancellablePromise<$models.GrokCapabilitiesCatalog> {
    return $Call.ByID(2350853243);
}

/**
 * ReadGrokGlobalInstructions returns personal Grok rules (~/.grok/AGENTS.md).
 * Official Grok Build loads home-level AGENTS*.md and ~/.grok/rules/*.md.
 */
export function ReadGrokGlobalInstructions(): $CancellablePromise<$models.GlobalInstructionsInfo> {
    return $Call.ByID(324441159);
}

/**
 * ReadGrokProjectInstructions returns AGENTS.md for the active Grok workspace.
 */
export function ReadGrokProjectInstructions(): $CancellablePromise<$models.ProjectInstructionsInfo> {
    return $Call.ByID(2285358151);
}

export function ReadGrokSession(backend: string, sessionID: string): $CancellablePromise<$models.GrokSessionDetail> {
    return $Call.ByID(2063656043, backend, sessionID);
}

export function ReadGrokSessionHistory(backend: string, sessionID: string, before: number): $CancellablePromise<$models.GrokSessionDetail> {
    return $Call.ByID(1433908917, backend, sessionID, before);
}

export function ReadGrokTurnLiveness(ref: $models.GrokTurnRef): $CancellablePromise<$models.TurnLivenessView> {
    return $Call.ByID(946330735, ref);
}

/**
 * ReadProjectInstructions returns the current workspace AGENTS.md content.
 */
export function ReadProjectInstructions(): $CancellablePromise<$models.ProjectInstructionsInfo> {
    return $Call.ByID(1112136990);
}

export function ReadProviderRouterConfig(): $CancellablePromise<$models.ProviderRouterView> {
    return $Call.ByID(42185596);
}

/**
 * ReadRuntimeAccountUsage keeps split-pane usage cards scoped to their own
 * provider instead of leaking the globally active provider's counters.
 */
export function ReadRuntimeAccountUsage(runtimeName: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3422692968, runtimeName);
}

export function ReadThread(threadID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3198804358, threadID);
}

/**
 * ReadThreadHistory returns the page immediately before a previously opened
 * Codex page. The complete app-server snapshot stays in Go so the webview never
 * has to deserialize an entire long conversation at once.
 */
export function ReadThreadHistory(threadID: string, before: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2666883278, threadID, before);
}

/**
 * ReadThreadLiveness bypasses ReadThread's display cache and answers only
 * whether this exact session still owns backend work.
 */
export function ReadThreadLiveness(threadID: string): $CancellablePromise<$models.TurnLivenessView> {
    return $Call.ByID(556638031, threadID);
}

export function ReadWorkspaceDiff(relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(3681597200, relativePath);
}

/**
 * RecordLocalTurnUsage lets the frontend persist per-turn totals (belt-and-suspenders with event hook).
 * Always attributes to the Codex runtime (frontend Codex store only calls this).
 */
export function RecordLocalTurnUsage(threadID: string, turnID: string, totalTokens: number): $CancellablePromise<void> {
    return $Call.ByID(657737560, threadID, turnID, totalTokens);
}

/**
 * RecordLocalTurnUsageDetailed persists a full input/output/cache/reasoning breakdown for a runtime.
 */
export function RecordLocalTurnUsageDetailed(runtime: string, threadID: string, turnID: string, inputTokens: number, cachedInputTokens: number, outputTokens: number, reasoningOutputTokens: number, totalTokens: number): $CancellablePromise<void> {
    return $Call.ByID(219955952, runtime, threadID, turnID, inputTokens, cachedInputTokens, outputTokens, reasoningOutputTokens, totalTokens);
}

export function RefreshClaudeRuntime(): $CancellablePromise<$models.ClaudeRuntimeStatus> {
    return $Call.ByID(1371517301);
}

export function RefreshGrokRuntime(): $CancellablePromise<$models.GrokRuntimeStatus> {
    return $Call.ByID(1680332538);
}

/**
 * RefreshGrokRuntimeQuick checks only local configuration and executable
 * availability. Entering the Grok workspace must not race a live turn with the
 * slower `grok models` authentication probe.
 */
export function RefreshGrokRuntimeQuick(): $CancellablePromise<$models.GrokRuntimeStatus> {
    return $Call.ByID(2885109357);
}

export function RefreshMCPServers(): $CancellablePromise<void> {
    return $Call.ByID(2777201397);
}

export function RefreshTerminalProfiles(): $CancellablePromise<$models.TerminalProfile[] | null> {
    return $Call.ByID(3551080407);
}

export function RefreshWorkspace(): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(2632368162);
}

export function ReloadProviderConfiguration(providerID: string): $CancellablePromise<$models.ProviderApplyResult> {
    return $Call.ByID(1515072116, providerID);
}

/**
 * RemoveClaudeMCPServer removes a user-scope MCP server.
 */
export function RemoveClaudeMCPServer(name: string): $CancellablePromise<void> {
    return $Call.ByID(2851080571, name);
}

/**
 * RemoveExternalMCPServer deletes one MCP server from the Gemini / OpenCode
 * JSON config.
 */
export function RemoveExternalMCPServer(runtime: string, scope: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(4247289240, runtime, scope, name);
}

/**
 * RemoveGrokMCPServer removes a user-scope MCP server.
 */
export function RemoveGrokMCPServer(name: string): $CancellablePromise<void> {
    return $Call.ByID(3470221360, name);
}

export function RenameClaudeSession(sessionID: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2613138530, sessionID, name);
}

/**
 * RenameGrokSession updates the session title (native summary.json + local override).
 */
export function RenameGrokSession(backend: string, sessionID: string, name: string): $CancellablePromise<$models.GrokSessionSummary> {
    return $Call.ByID(2689730813, backend, sessionID, name);
}

export function ResetProviderRouterCircuits(): $CancellablePromise<$models.ProviderRouterView> {
    return $Call.ByID(4098080945);
}

export function ResizeTerminal(processID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(253488878, processID, rows, cols);
}

export function ResolveServerRequest(requestKey: string, result: { [_ in string]?: any } | null): $CancellablePromise<void> {
    return $Call.ByID(3513618634, requestKey, result);
}

export function RestartProvider(providerID: string): $CancellablePromise<$models.ProviderApplyResult> {
    return $Call.ByID(360590612, providerID);
}

export function RestoreCodexProviderRoute(): $CancellablePromise<$models.ProviderRouterView> {
    return $Call.ByID(70883791);
}

export function ResumeThread(threadID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3830793425, threadID);
}

export function RollbackThread(threadID: string, numTurns: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4017068374, threadID, numTurns);
}

export function SaveClaudeGlobalInstructions(content: string): $CancellablePromise<$models.GlobalInstructionsInfo> {
    return $Call.ByID(3048108819, content);
}

export function SaveClaudeProjectInstructions(content: string): $CancellablePromise<$models.ProjectInstructionsInfo> {
    return $Call.ByID(4083074467, content);
}

export function SaveCodexFeatureFlags(flags: $models.CodexFeatureFlags): $CancellablePromise<$models.CodexFeatureFlags> {
    return $Call.ByID(199517151, flags);
}

export function SaveExternalRuntimeInstructions(request: $models.ExternalInstructionsSaveRequest): $CancellablePromise<void> {
    return $Call.ByID(1994634985, request);
}

export function SaveExternalRuntimeMCP(request: $models.ExternalMCPJSONSaveRequest): $CancellablePromise<void> {
    return $Call.ByID(1700593124, request);
}

/**
 * SaveGlobalInstructions writes personal Codex AGENTS.md and mirrors settings cache.
 */
export function SaveGlobalInstructions(content: string): $CancellablePromise<$models.GlobalInstructionsInfo> {
    return $Call.ByID(4035646133, content);
}

export function SaveGrokGlobalInstructions(content: string): $CancellablePromise<$models.GlobalInstructionsInfo> {
    return $Call.ByID(1655319778, content);
}

export function SaveGrokProjectInstructions(content: string): $CancellablePromise<$models.ProjectInstructionsInfo> {
    return $Call.ByID(363786212, content);
}

export function SavePreferences(settings: $models.UserSettings): $CancellablePromise<$models.UserSettings> {
    return $Call.ByID(3258666379, settings);
}

/**
 * SaveProjectInstructions writes the current workspace AGENTS.md (project-scoped Codex guidance).
 */
export function SaveProjectInstructions(content: string): $CancellablePromise<$models.ProjectInstructionsInfo> {
    return $Call.ByID(437632509, content);
}

export function SaveProviderRouterConfig(request: $models.ProviderRouterSaveRequest): $CancellablePromise<$models.ProviderRouterView> {
    return $Call.ByID(526581077, request);
}

export function SaveScheduledTask(task: $models.ScheduledTask): $CancellablePromise<$models.ScheduledTask> {
    return $Call.ByID(993084139, task);
}

/**
 * SelectBrowserDownloadDir opens a folder picker for the preferred download directory.
 */
export function SelectBrowserDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(3603113877);
}

export function SelectClaudeWorkspace(): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(3764125613);
}

/**
 * SelectComposerFiles keeps image attachments on the managed attachment path
 * and returns other user-selected files as explicit context paths.
 */
export function SelectComposerFiles(): $CancellablePromise<$models.ComposerFileSelection> {
    return $Call.ByID(733641159);
}

export function SelectGrokWorkspace(): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(1796203834);
}

export function SelectImages(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1863599724);
}

export function SelectWorkspace(): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(3302172243);
}

export function SendClaudeMessage(request: $models.ClaudeSendRequest): $CancellablePromise<$models.ClaudeTurnRef> {
    return $Call.ByID(454475273, request);
}

export function SendGrokMessage(request: $models.GrokSendRequest): $CancellablePromise<$models.GrokTurnRef> {
    return $Call.ByID(3724715910, request);
}

export function SendMessage(request: $models.SendMessageRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4154529951, request);
}

export function SetActiveRuntime(runtimeID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(610883024, runtimeID);
}

export function SetAlwaysOnTop(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4224477541, enabled);
}

export function SetAppEnabled(appID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2274727570, appID, enabled);
}

export function SetExperimentalFeature(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3348439094, name, enabled);
}

export function SetHookEnabled(hookKey: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(133382174, hookKey, enabled);
}

/**
 * SetPreventSleepActive keeps the machine awake while a Codex turn is running
 * when the user enabled Prevent sleep while running.
 */
export function SetPreventSleepActive(active: boolean): $CancellablePromise<void> {
    return $Call.ByID(3145083505, active);
}

export function SetSkillEnabled(request: $models.SkillConfigRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1157345440, request);
}

export function SetThreadName(threadID: string, name: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2720604333, threadID, name);
}

export function Settings(): $CancellablePromise<$models.UserSettings> {
    return $Call.ByID(3630548879);
}

export function StartChatGPTLogin(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2314466290);
}

export function StartCodex(workspace: string): $CancellablePromise<void> {
    return $Call.ByID(2359008005, workspace);
}

export function StartMCPLogin(name: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3505393243, name);
}

export function StartReview(request: $models.ReviewStartRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3832632170, request);
}

export function StartTerminalSession(processID: string): $CancellablePromise<void> {
    return $Call.ByID(3883042926, processID);
}

export function SteerTurn(request: $models.SteerTurnRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2094286076, request);
}

export function StopCodex(): $CancellablePromise<void> {
    return $Call.ByID(712065861);
}

export function StopTerminalSession(processID: string): $CancellablePromise<void> {
    return $Call.ByID(1898194606, processID);
}

export function SwitchGitBranch(request: $models.GitBranchSwitchRequest): $CancellablePromise<$models.GitActionResult> {
    return $Call.ByID(1528710970, request);
}

export function UnarchiveClaudeSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3713905517, sessionID);
}

/**
 * UnarchiveGrokSession restores a session to the main list.
 */
export function UnarchiveGrokSession(backend: string, sessionID: string): $CancellablePromise<$models.GrokSessionSummary> {
    return $Call.ByID(677986454, backend, sessionID);
}

export function UnarchiveThread(threadID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1003864789, threadID);
}

export function UninstallPlugin(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(1232784559, pluginID);
}

export function UpdateProviderContextPolicy(providerID: string, tokens: number, threshold: number, autoCompactEnabled: boolean, pruneEnabled: boolean, thresholdScope: string): $CancellablePromise<$models.ProviderApplyResult> {
    return $Call.ByID(2761509943, providerID, tokens, threshold, autoCompactEnabled, pruneEnabled, thresholdScope);
}

export function UpdateSessionMemories(request: $models.SessionMemoriesRequest): $CancellablePromise<void> {
    return $Call.ByID(2079433278, request);
}

export function UpdateSessionPreferences(request: $models.SessionPreferencesRequest): $CancellablePromise<void> {
    return $Call.ByID(3877948261, request);
}

export function UpdateStatus(): $CancellablePromise<$models.UpdateProgress> {
    return $Call.ByID(3590124437);
}

/**
 * UpsertClaudeMCPServer adds or updates a user-scope MCP server via
 * `claude mcp add-json` so the CLI owns the exact settings format.
 */
export function UpsertClaudeMCPServer(input: $models.MCPServerInput): $CancellablePromise<void> {
    return $Call.ByID(1256922634, input);
}

/**
 * UpsertExternalMCPServer adds or updates one MCP server in the Gemini /
 * OpenCode JSON config, preserving every unrelated key.
 */
export function UpsertExternalMCPServer(runtime: string, scope: string, input: $models.MCPServerInput): $CancellablePromise<void> {
    return $Call.ByID(2226446489, runtime, scope, input);
}

/**
 * UpsertGrokMCPServer adds or updates a user-scope MCP server via
 * `grok mcp add`. The CLI writes ~/.grok/config.toml itself, which avoids
 * hand-editing TOML.
 */
export function UpsertGrokMCPServer(input: $models.MCPServerInput): $CancellablePromise<void> {
    return $Call.ByID(3836990317, input);
}

export function UpsertMCPServer(request: $models.MCPServerWriteRequest): $CancellablePromise<void> {
    return $Call.ByID(4078237320, request);
}

export function UseClaudeWorkspace(path: string): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(1983556052, path);
}

export function UseGrokWorkspace(path: string): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(2288325727, path);
}

export function UseWorkspace(path: string): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(2106688622, path);
}

export function WriteTerminal(processID: string, input: string): $CancellablePromise<void> {
    return $Call.ByID(587545473, processID, input);
}
