// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as codex$0 from "./internal/codex/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(257367811);
}

export function ApplyUpdateAndRestart(): $CancellablePromise<void> {
    return $Call.ByID(3133742711);
}

export function ArchiveThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(404527456, threadID);
}

/**
 * AttachImageData saves a pasted/dropped image into the NiceCodex temp folder
 * and registers it for SendMessage (same allow-list as SelectImages).
 */
export function AttachImageData(fileName: string, mimeType: string, dataBase64: string): $CancellablePromise<string> {
    return $Call.ByID(3374776048, fileName, mimeType, dataBase64);
}

export function Bootstrap(): $CancellablePromise<$models.BootstrapData> {
    return $Call.ByID(4177956144);
}

export function BrowserBack(): $CancellablePromise<void> {
    return $Call.ByID(193132621);
}

export function BrowserForward(): $CancellablePromise<void> {
    return $Call.ByID(1722237139);
}

export function BrowserReload(): $CancellablePromise<void> {
    return $Call.ByID(2544793859);
}

export function CancelUpdateDownload(): $CancellablePromise<void> {
    return $Call.ByID(1670800741);
}

export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(3671876993);
}

export function CodexStatus(): $CancellablePromise<codex$0.Status> {
    return $Call.ByID(3760924599);
}

export function CommitGitChanges(request: $models.GitCommitRequest): $CancellablePromise<$models.GitActionResult> {
    return $Call.ByID(3986674178, request);
}

export function CompactThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(2159280559, threadID);
}

export function CreateGitBranch(request: $models.GitBranchRequest): $CancellablePromise<$models.GitActionResult> {
    return $Call.ByID(376396278, request);
}

export function CreateThread(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1065248874);
}

export function DeleteMCPServer(name: string): $CancellablePromise<void> {
    return $Call.ByID(1611204592, name);
}

export function DeleteScheduledTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3352537869, id);
}

export function DeleteThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(1472565121, threadID);
}

export function DownloadAndStageUpdate(): $CancellablePromise<$models.UpdateProgress> {
    return $Call.ByID(3358895366);
}

export function FocusBrowser(): $CancellablePromise<void> {
    return $Call.ByID(1719904498);
}

export function ForkThread(threadID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1034771762, threadID);
}

export function InstallPlugin(request: $models.PluginInstallRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3003226110, request);
}

export function InterruptTurn(threadID: string, turnID: string): $CancellablePromise<void> {
    return $Call.ByID(935266466, threadID, turnID);
}

export function ListApps(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2844972250);
}

export function ListArchivedThreads(search: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(795343881, search);
}

export function ListCollaborationModes(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2846685189);
}

export function ListExperimentalFeatures(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(626848283);
}

export function ListHooks(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2720002358);
}

export function ListLocalMemories(): $CancellablePromise<$models.MemoriesOverview> {
    return $Call.ByID(1204786654);
}

export function ListMCPServerStatus(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2306388879);
}

export function ListMCPServers(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1027663362);
}

export function ListModelProviders(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2342522979);
}

export function ListModels(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4263467744);
}

export function ListPlugins(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(442045366);
}

export function ListScheduledTasks(): $CancellablePromise<$models.ScheduledTask[] | null> {
    return $Call.ByID(2711200733);
}

export function ListSkills(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3162367268);
}

export function ListSystemFonts(): $CancellablePromise<$models.SystemFont[] | null> {
    return $Call.ByID(1974567495);
}

export function ListThreads(search: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3185449219, search);
}

export function ListWorkspaceThreads(workspace: string, search: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2536997788, workspace, search);
}

export function LogoutAccount(): $CancellablePromise<void> {
    return $Call.ByID(2683059787);
}

export function OpenBrowser(rawURL: string): $CancellablePromise<string> {
    return $Call.ByID(3692280918, rawURL);
}

export function OpenBrowserDevTools(): $CancellablePromise<void> {
    return $Call.ByID(1516554564);
}

/**
 * OpenBrowserDownloadDir reveals the configured download folder in the OS file manager.
 */
export function OpenBrowserDownloadDir(): $CancellablePromise<void> {
    return $Call.ByID(4097011765);
}

export function OpenExternal(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(2121391737, rawURL);
}

export function OpenMemoriesFolder(): $CancellablePromise<void> {
    return $Call.ByID(2340956881);
}

export function OpenTerminal(): $CancellablePromise<void> {
    return $Call.ByID(3614603658);
}

/**
 * PreviewImage returns a data-URL for an allow-listed attachment so the UI can show thumbnails.
 */
export function PreviewImage(path: string): $CancellablePromise<string> {
    return $Call.ByID(2624332779, path);
}

export function PushGitBranch(): $CancellablePromise<$models.GitActionResult> {
    return $Call.ByID(2060389666);
}

export function ReadAccount(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3417819837);
}

export function ReadAccountRateLimits(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3284885595);
}

/**
 * ReadAccountUsage prefers local usage.json.
 * When empty, it backfills from ~/.codex session rollouts (true local history),
 * then optionally seeds from ChatGPT account/usage/read as a fallback.
 */
export function ReadAccountUsage(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3812997328);
}

export function ReadCodexFeatureFlags(): $CancellablePromise<$models.CodexFeatureFlags> {
    return $Call.ByID(1079251556);
}

/**
 * ReadGlobalInstructions returns personal Codex AGENTS.md content from disk.
 */
export function ReadGlobalInstructions(): $CancellablePromise<$models.GlobalInstructionsInfo> {
    return $Call.ByID(2724052924);
}

/**
 * ReadProjectInstructions returns the current workspace AGENTS.md content.
 */
export function ReadProjectInstructions(): $CancellablePromise<$models.ProjectInstructionsInfo> {
    return $Call.ByID(1112136990);
}

export function ReadThread(threadID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3198804358, threadID);
}

export function ReadWorkspaceDiff(relativePath: string): $CancellablePromise<string> {
    return $Call.ByID(3681597200, relativePath);
}

/**
 * RecordLocalTurnUsage lets the frontend persist per-turn totals (belt-and-suspenders with event hook).
 */
export function RecordLocalTurnUsage(threadID: string, turnID: string, totalTokens: number): $CancellablePromise<void> {
    return $Call.ByID(657737560, threadID, turnID, totalTokens);
}

export function RefreshMCPServers(): $CancellablePromise<void> {
    return $Call.ByID(2777201397);
}

export function RefreshWorkspace(): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(2632368162);
}

export function ResizeTerminal(processID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(253488878, processID, rows, cols);
}

export function ResolveServerRequest(requestKey: string, result: { [_ in string]?: any } | null): $CancellablePromise<void> {
    return $Call.ByID(3513618634, requestKey, result);
}

export function ResumeThread(threadID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3830793425, threadID);
}

export function RollbackThread(threadID: string, numTurns: number): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4017068374, threadID, numTurns);
}

export function SaveCodexFeatureFlags(flags: $models.CodexFeatureFlags): $CancellablePromise<$models.CodexFeatureFlags> {
    return $Call.ByID(199517151, flags);
}

/**
 * SaveGlobalInstructions writes personal Codex AGENTS.md and mirrors settings cache.
 */
export function SaveGlobalInstructions(content: string): $CancellablePromise<$models.GlobalInstructionsInfo> {
    return $Call.ByID(4035646133, content);
}

export function SavePreferences(settings: $models.UserSettings): $CancellablePromise<$models.UserSettings> {
    return $Call.ByID(3258666379, settings);
}

/**
 * SaveProjectInstructions writes the current workspace AGENTS.md (project-scoped Codex guidance).
 */
export function SaveProjectInstructions(content: string): $CancellablePromise<$models.ProjectInstructionsInfo> {
    return $Call.ByID(437632509, content);
}

export function SaveScheduledTask(task: $models.ScheduledTask): $CancellablePromise<$models.ScheduledTask> {
    return $Call.ByID(993084139, task);
}

/**
 * SelectBrowserDownloadDir opens a folder picker for the preferred download directory.
 */
export function SelectBrowserDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(3603113877);
}

export function SelectImages(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1863599724);
}

export function SelectWorkspace(): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(3302172243);
}

export function SendMessage(request: $models.SendMessageRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(4154529951, request);
}

export function SetAlwaysOnTop(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4224477541, enabled);
}

export function SetAppEnabled(appID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2274727570, appID, enabled);
}

export function SetExperimentalFeature(name: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3348439094, name, enabled);
}

export function SetHookEnabled(hookKey: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(133382174, hookKey, enabled);
}

/**
 * SetPreventSleepActive keeps the machine awake while a Codex turn is running
 * when the user enabled Prevent sleep while running.
 */
export function SetPreventSleepActive(active: boolean): $CancellablePromise<void> {
    return $Call.ByID(3145083505, active);
}

export function SetSkillEnabled(request: $models.SkillConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(1157345440, request);
}

export function SetThreadName(threadID: string, name: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2720604333, threadID, name);
}

export function Settings(): $CancellablePromise<$models.UserSettings> {
    return $Call.ByID(3630548879);
}

export function StartChatGPTLogin(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2314466290);
}

export function StartCodex(workspace: string): $CancellablePromise<void> {
    return $Call.ByID(2359008005, workspace);
}

export function StartMCPLogin(name: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3505393243, name);
}

export function StartReview(request: $models.ReviewStartRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3832632170, request);
}

export function StartTerminalSession(processID: string): $CancellablePromise<void> {
    return $Call.ByID(3883042926, processID);
}

export function SteerTurn(request: $models.SteerTurnRequest): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(2094286076, request);
}

export function StopCodex(): $CancellablePromise<void> {
    return $Call.ByID(712065861);
}

export function StopTerminalSession(processID: string): $CancellablePromise<void> {
    return $Call.ByID(1898194606, processID);
}

export function UnarchiveThread(threadID: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1003864789, threadID);
}

export function UninstallPlugin(pluginID: string): $CancellablePromise<void> {
    return $Call.ByID(1232784559, pluginID);
}

export function UpdateSessionMemories(request: $models.SessionMemoriesRequest): $CancellablePromise<void> {
    return $Call.ByID(2079433278, request);
}

export function UpdateSessionPreferences(request: $models.SessionPreferencesRequest): $CancellablePromise<void> {
    return $Call.ByID(3877948261, request);
}

export function UpdateStatus(): $CancellablePromise<$models.UpdateProgress> {
    return $Call.ByID(3590124437);
}

export function UpsertMCPServer(request: $models.MCPServerWriteRequest): $CancellablePromise<void> {
    return $Call.ByID(4078237320, request);
}

export function UseWorkspace(path: string): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(2106688622, path);
}

export function WriteTerminal(processID: string, input: string): $CancellablePromise<void> {
    return $Call.ByID(587545473, processID, input);
}
