// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as codex$0 from "./internal/codex/models.js";

export interface AgentProviderModel {
    "model": string;
    "providerId"?: string;
    "displayName": string;
    "description": string;
    "isDefault": boolean;
    "contextWindow": number;
}

export interface AgentProviderReasoningEffort {
    "effort": string;
    "displayName": string;
    "description": string;
    "isDefault": boolean;
}

export interface AgentProviderRuntime {
    "id": string;
    "name": string;
    "kind": string;
    "installed": boolean;
    "healthy": boolean;
    "runtimeReady": boolean;
    "version": string;
    "executable": string;
    "status": string;
    "message": string;
    "capabilities": string[] | null;
    "models": AgentProviderModel[] | null;
    "reasoningEfforts": AgentProviderReasoningEffort[] | null;

    /**
     * Providers is populated by runtimes that expose their own provider catalog
     * (currently OpenCode). It is deliberately separate from Codex's provider
     * field so external CLIs keep their native provider/model identity.
     */
    "providers"?: ExternalProviderView[] | null;
}

export interface BootstrapData {
    "codex": codex$0.Detection;
    "grok": GrokRuntimeStatus;
    "agentProviders": AgentProviderRuntime[] | null;
    "settings": UserSettings;
    "workspace"?: WorkspaceInfo | null;
    "terminalProfiles": TerminalProfile[] | null;
    "appVersion": string;
    "updateRepo": string;
}

/**
 * CLIToolActionResult is returned after install / update.
 */
export interface CLIToolActionResult {
    "ok": boolean;
    "message": string;
    "output": string;
    "tool": CLIToolStatus;
}

/**
 * CLIToolStatus describes install / update state for one CLI.
 */
export interface CLIToolStatus {
    "id": string;
    "name": string;
    "package": string;
    "installCommand": string;
    "installed": boolean;
    "executable": string;
    "version": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "packageManager": string;
    "message": string;
    "canInstall": boolean;
    "nodeAvailable": boolean;
}

/**
 * CLIToolsReport is the aggregate response for CheckCLITools.
 */
export interface CLIToolsReport {
    "tools": CLIToolStatus[] | null;
    "packageManager": string;
    "nodeAvailable": boolean;
    "nodeVersion": string;
    "checkedAt": number;

    /**
     * Platform is GOOS: windows | darwin | linux — for UI install hints.
     */
    "platform": string;

    /**
     * Config homes (env override aware) so Settings can show real paths on each OS.
     */
    "codexHome": string;
    "claudeHome": string;
    "grokHome": string;
    "geminiHome": string;
    "openCodeHome": string;
}

/**
 * ClaudeAgentView is a custom agent under ~/.claude/agents or project.
 */
export interface ClaudeAgentView {
    "name": string;
    "displayName": string;
    "description": string;
    "path": string;
    "scope": string;
}

/**
 * ClaudeCapabilitiesCatalog powers the Claude capability center (aligned with ~/.claude layout).
 */
export interface ClaudeCapabilitiesCatalog {
    "runtime": ClaudeRuntimeStatus;
    "configPath": string;
    "claudeHome": string;
    "claudeJsonPath": string;
    "settings": ClaudeSettingsSummary;
    "mcp": ClaudeMCPServerView[] | null;
    "skills": ClaudeSkillView[] | null;
    "plugins": ClaudePluginView[] | null;
    "agents": ClaudeAgentView[] | null;
    "commands": ClaudeCommandView[] | null;
    "hooks": ClaudeHookView[] | null;
    "globalInstructions": GlobalInstructionsInfo;
    "projectInstructions": ProjectInstructionsInfo;
}

/**
 * ClaudeCommandView is a slash command / skill alias under commands/.
 */
export interface ClaudeCommandView {
    "name": string;
    "path": string;
    "scope": string;
}

export interface ClaudeCompactionResult {
    "preTokens": number;
    "postTokens": number;
    "trigger": string;
}

/**
 * ClaudeHookView summarizes configured hooks from settings.json.
 */
export interface ClaudeHookView {
    "event": string;
    "command": string;
    "source": string;
}

/**
 * ClaudeMCPServerView is an MCP server discovered from Claude Code config.
 */
export interface ClaudeMCPServerView {
    "name": string;
    "enabled": boolean;
    "command": string;
    "args": string;
    "transport": string;
    "url": string;

    /**
     * user | project
     */
    "scope": string;
    "source": string;
}

/**
 * ClaudeMessage is one timeline row stored with a session.
 */
export interface ClaudeMessage {
    "id": string;
    "role": string;
    "text": string;
    "toolName"?: string;
    "status"?: string;
    "createdAt": number;
    "contextTokens"?: number;
}

/**
 * ClaudePluginView is an installed Claude Code plugin.
 */
export interface ClaudePluginView {
    "name": string;
    "version": string;
    "scope": string;
    "path": string;
}

/**
 * ClaudeRuntimeStatus is the live probe for Claude Code CLI.
 */
export interface ClaudeRuntimeStatus {
    "available": boolean;
    "authenticated": boolean;
    "version": string;
    "executable": string;
    "message": string;
}

/**
 * ClaudeSendRequest starts a Claude Code turn.
 */
export interface ClaudeSendRequest {
    "sessionId": string;
    "workspace": string;
    "text": string;
    "images": string[] | null;
    "model": string;
    "effort": string;
    "clientTurnId"?: string;
}

/**
 * ClaudeSessionDetail is one page of an open conversation.
 */
export interface ClaudeSessionDetail {
    "summary": ClaudeSessionSummary;
    "messages": ClaudeMessage[] | null;
    "historyStart": number;
    "historyTotal": number;
    "historyTurnOffset": number;
    "hasEarlier": boolean;
    "activeTurnId"?: string;
}

/**
 * ClaudeSessionSummary is a sidebar row for Claude history.
 */
export interface ClaudeSessionSummary {
    "id": string;
    "workspace": string;
    "name": string;
    "preview": string;
    "model": string;
    "effort": string;
    "createdAt": number;
    "updatedAt": number;
    "activeTurnId"?: string;
}

/**
 * ClaudeSettingsSummary is a safe subset of ~/.claude/settings.json for the UI.
 */
export interface ClaudeSettingsSummary {
    "path": string;
    "exists": boolean;
    "model": string;
    "permissionMode": string;
    "allowRules": number;
    "denyRules": number;
    "envKeys": string[] | null;
    "baseURL": string;
    "skipDangerPrompt": boolean;
    "hasStatusLine": boolean;
    "rawPermissionMode": string;
}

/**
 * ClaudeSkillView is a Claude skill (SKILL.md) under ~/.claude/skills or project.
 */
export interface ClaudeSkillView {
    "name": string;
    "displayName": string;
    "description": string;
    "path": string;

    /**
     * user | project | plugin
     */
    "scope": string;
}

/**
 * ClaudeTurnRef identifies a running turn.
 */
export interface ClaudeTurnRef {
    "sessionId": string;
    "turnId": string;
}

export interface CodexFeatureFlags {
    "memoriesEnabled": boolean;
    "memoriesGenerate": boolean;
    "memoriesUse": boolean;
    "memoriesDisableExternalContext": boolean;
    "browserUseFullCDP": boolean;
    "inAppBrowser": boolean;
}

export interface ComposerFileSelection {
    "images": string[] | null;
    "files": string[] | null;
}

export interface ExternalInstructionsSaveRequest {
    "runtime": string;
    "workspace": string;

    /**
     * global | project
     */
    "scope": string;
    "content": string;
}

export interface ExternalMCPJSONSaveRequest {
    "runtime": string;
    "workspace": string;

    /**
     * global | project
     */
    "scope": string;
    "json": string;
}

export interface ExternalMCPServerView {
    "name": string;
    "enabled": boolean;
    "type": string;
    "command": string;
    "args": string;
    "url": string;
    "transport": string;
    "configPath": string;
    "source": string;
}

export interface ExternalProviderView {
    "id": string;
    "name": string;
    "source": string;
    "configured": boolean;
    "authenticated": boolean;
    "baseUrl"?: string;
    "models": AgentProviderModel[] | null;
}

export interface ExternalRuntimeCatalog {
    "runtime": string;
    "workspace": string;
    "nativeHome": string;
    "configPath": string;
    "activeProvider": string;
    "defaultModel": string;
    "providerSource": string;
    "providers": ExternalProviderView[] | null;
    "models": AgentProviderModel[] | null;
    "mcp": ExternalMCPServerView[] | null;
    "globalInstructions": GlobalInstructionsInfo;
    "projectInstructions": ProjectInstructionsInfo;
    "configInstructions"?: string;
    "sessions": ExternalSessionView[] | null;
    "usage": ExternalUsageSummary;
    "readOnlyNotice"?: string;
}

export interface ExternalSessionView {
    "id": string;
    "title": string;
    "preview": string;
    "workspace": string;
    "provider": string;
    "model": string;
    "createdAt": number;
    "updatedAt": number;
    "native": boolean;
}

export interface ExternalUsageDailyBucket {
    "startDate": string;
    "tokens": number;
    "inputTokens"?: number;
    "cachedInputTokens"?: number;
    "outputTokens"?: number;
    "reasoningOutputTokens"?: number;
}

export interface ExternalUsageModelView {
    "model": string;
    "provider": string;
    "sessions": number;
    "inputTokens": number;
    "outputTokens": number;
    "reasoningTokens": number;
    "cachedTokens": number;
    "totalTokens": number;
    "cost": number;
}

export interface ExternalUsageSummary {
    "rangeDays": number;
    "sessions": number;
    "messages": number;
    "inputTokens": number;
    "outputTokens": number;
    "reasoningTokens": number;
    "cachedTokens": number;
    "totalTokens": number;
    "cost": number;
    "byModel": ExternalUsageModelView[] | null;
    "dailyUsageBuckets": ExternalUsageDailyBucket[] | null;
    "source": string;
}

export interface GitActionResult {
    "ok": boolean;
    "message": string;
    "branch"?: string;
    "prUrl"?: string;
}

export interface GitBranchRequest {
    "name": string;
}

export interface GitBranchSwitchRequest {
    "workspace": string;
    "name": string;
}

export interface GitChange {
    "status": string;
    "path": string;
}

export interface GitCommitRequest {
    "message": string;
}

export interface GitHubIssueContent {
    "number": number;
    "title": string;
    "body": string;
    "url": string;
    "state": string;
    "author": string;
    "labels": string[] | null;
}

export interface GitHubIssueImportContext {
    "available": boolean;
    "ownerRepo": string;
    "remoteUrl": string;
    "reason"?: string;
}

/**
 * GlobalInstructionsInfo is the personal Codex AGENTS.md under CODEX_HOME.
 */
export interface GlobalInstructionsInfo {
    "content": string;
    "path": string;
    "source": string;
    "exists": boolean;
    "emptyFile": boolean;
    "available": boolean;
}

/**
 * GrokCapabilitiesCatalog is the Grok-mode capability center payload.
 */
export interface GrokCapabilitiesCatalog {
    "runtime": GrokRuntimeStatus;
    "configPath": string;
    "grokHome": string;
    "mcp": GrokMCPServerView[] | null;
    "skills": GrokSkillView[] | null;
    "plugins": GrokPluginView[] | null;
    "globalInstructions": GlobalInstructionsInfo;
    "projectInstructions": ProjectInstructionsInfo;
}

/**
 * GrokMCPServerView is a server entry from ~/.grok/config.toml [mcp_servers.*].
 */
export interface GrokMCPServerView {
    "name": string;
    "enabled": boolean;
    "command": string;
    "args": string;
    "transport": string;
    "url": string;
}

export interface GrokMessage {
    "id": string;
    "role": string;
    "text": string;
    "images"?: string[] | null;
    "toolName"?: string;

    /**
     * ToolKind classifies Grok Build tools for the workbench timeline:
     * file | command | search | mcp | tool
     */
    "toolKind"?: string;
    "command"?: string;
    "path"?: string;
    "detail"?: string;
    "diff"?: string;
    "status"?: string;
    "createdAt": number;
}

/**
 * GrokPluginView is an installed Grok plugin package.
 */
export interface GrokPluginView {
    "name": string;
    "path": string;
}

export interface GrokRuntimeStatus {
    "buildAvailable": boolean;
    "buildAuthenticated": boolean;
    "buildVersion": string;
    "buildExecutable": string;
    "apiConfigured": boolean;
}

export interface GrokSendRequest {
    "backend": string;
    "sessionId": string;
    "workspace": string;
    "text": string;
    "images": string[] | null;
    "model": string;
    "effort": string;
    "clientTurnId"?: string;
}

export interface GrokSessionDetail {
    "summary": GrokSessionSummary;
    "messages": GrokMessage[] | null;
    "historyStart": number;
    "historyTotal": number;
    "historyTurnOffset": number;
    "hasEarlier": boolean;
    "activeTurnId"?: string;
}

export interface GrokSessionSummary {
    "id": string;
    "backend": string;
    "workspace": string;
    "name": string;
    "preview": string;
    "model": string;
    "effort": string;
    "createdAt": number;
    "updatedAt": number;
    "activeTurnId"?: string;
}

/**
 * GrokSkillView is a discovered Grok skill (SKILL.md).
 */
export interface GrokSkillView {
    "name": string;
    "displayName": string;
    "description": string;
    "path": string;

    /**
     * user | project
     */
    "scope": string;
}

export interface GrokTurnRef {
    "backend": string;
    "sessionId": string;
    "turnId": string;
}

export interface MCPServerWriteRequest {
    "name": string;
    "enabled": boolean;
    "command": string;
    "args": string[] | null;
    "url": string;
    "transport": string;
    "env": { [_ in string]?: string } | null;
}

export interface MCPServersImportRequest {
    "servers": MCPServerWriteRequest[] | null;
}

export interface MemoriesOverview {
    "root": string;
    "enabled": boolean;
    "generate": boolean;
    "use": boolean;
    "files": MemoryFileInfo[] | null;
    "summaryPreview": string;
}

export interface MemoryFileInfo {
    "name": string;
    "path": string;
    "size": number;
    "preview": string;
}

export interface PluginInstallRequest {
    "pluginName": string;
    "marketplacePath": string;
    "remoteMarketplaceName": string;
}

/**
 * ProjectInstructionsInfo is the workspace-root AGENTS.md (project-scoped Codex guidance).
 */
export interface ProjectInstructionsInfo {
    "content": string;
    "workspace": string;
    "workspaceName": string;
    "path": string;
    "source": string;
    "exists": boolean;
    "emptyFile": boolean;
    "available": boolean;
}

export interface ProviderApplyResult {
    "providerId": string;
    "applyLevel": string;
    "restartRequired": boolean;
    "warnings": string[] | null;
    "configuration": ProviderConfigurationView;
}

export interface ProviderConfigurationView {
    "runtime": AgentProviderRuntime;
    "configPath": string;
    "modelSource": string;
    "applyLevel": string;
    "restartRequired": boolean;
    "canReload": boolean;
    "canRestart": boolean;
    "supportsModel": boolean;
    "supportsEffort": boolean;
    "permissionModes": string[] | null;
    "context": ProviderContextPolicyView;
    "warnings": string[] | null;
}

export interface ProviderContextPolicyView {
    "tokens": number;
    "configuredTokens": number;
    "source": string;
    "writable": boolean;
    "tokenMode": string;
    "tokenMinimum": number;
    "tokenMaximum": number;
    "tokenStep": number;
    "isFallback": boolean;
    "compactStrategy": string;
    "compactAvailable": boolean;
    "autoCompactSupported": boolean;
    "autoCompactEnabled": boolean;
    "autoCompactToggleable": boolean;
    "thresholdConfigurable": boolean;
    "thresholdConfigured": boolean;
    "autoCompactThreshold": number;
    "thresholdUnit": string;
    "thresholdMinimum": number;
    "thresholdMaximum": number;
    "thresholdStep": number;
    "thresholdScopeSupported": boolean;
    "thresholdScopeConfigured": boolean;
    "thresholdScope": string;
    "thresholdScopeOptions": string[] | null;
    "pruneSupported": boolean;
    "pruneEnabled": boolean;
    "description": string;
}

export interface ProviderRouterSaveRequest {
    "enabled": boolean;
    "port": number;
    "failureThreshold": number;
    "recoverySuccessThreshold": number;
    "cooldownSeconds": number;
    "firstByteTimeoutSeconds": number;
    "upstreams": ProviderRouterUpstreamInput[] | null;
}

export interface ProviderRouterUpstreamInput {
    "id": string;
    "name": string;
    "baseUrl": string;
    "apiKey": string;
    "keepExistingKey": boolean;
    "clearApiKey": boolean;
    "authMode": string;
    "enabled": boolean;
}

export interface ProviderRouterUpstreamView {
    "id": string;
    "name": string;
    "baseUrl": string;
    "authMode": string;
    "enabled": boolean;
    "hasApiKey": boolean;
    "state": string;
    "consecutiveFailures": number;
    "recoverySuccesses": number;
    "openUntil": number;
    "lastStatus": number;
    "lastLatencyMs": number;
    "lastError": string;
    "requestCount": number;
}

export interface ProviderRouterView {
    "enabled": boolean;
    "running": boolean;
    "port": number;
    "listenUrl": string;
    "failureThreshold": number;
    "recoverySuccessThreshold": number;
    "cooldownSeconds": number;
    "firstByteTimeoutSeconds": number;
    "codexApplied": boolean;
    "lastError": string;
    "currentProviders": ProviderRuntimeView[] | null;
    "upstreams": ProviderRouterUpstreamView[] | null;
}

export interface ProviderRuntimeView {
    "runtime": string;
    "provider": string;
    "name": string;
    "baseUrl": string;
    "configPath": string;
    "source": string;
    "configured": boolean;
}

export interface ReviewStartRequest {
    "threadId": string;
    "targetType": string;
    "branch": string;
    "instructions": string;
    "delivery": string;
}

export interface ScheduledTask {
    "id": string;
    "title": string;
    "prompt": string;
    "workspace": string;
    "enabled": boolean;
    "intervalMin": number;
    "useWorktree": boolean;
    "lastRunAt": number;
    "nextRunAt": number;
    "lastError"?: string;
    "createdAt": number;
    "updatedAt": number;
}

export interface SendMessageRequest {
    "threadId": string;
    "text": string;
    "images": string[] | null;

    /**
     * Per-turn mode override — mirrors official TUI SubmitUserMessageWithMode.
     */
    "collaborationMode"?: string;
}

export interface SessionMemoriesRequest {
    "sessionId": string;
    "useMemories": boolean | null;
    "generateMemories": boolean | null;
}

export interface SessionPreferencesRequest {
    "sessionId": string;
    "model": string;
    "effort": string;
    "collaborationMode": string;
}

export interface SkillConfigRequest {
    "name": string;
    "path": string;
    "enabled": boolean;
}

export interface SteerTurnRequest {
    "threadId": string;
    "turnId": string;
    "text": string;
    "images": string[] | null;
}

export interface SystemFont {
    "family": string;
    "source": string;
}

export interface TerminalProfile {
    "id": string;
    "name": string;
    "description": string;
    "available": boolean;
}

/**
 * TurnLivenessView is the authoritative process/app-server state for one session.
 * It intentionally excludes cached history, which can retain stale in-progress rows.
 */
export interface TurnLivenessView {
    "running": boolean;
    "turnId"?: string;
    "latestTurnId"?: string;
    "latestTurnStatus"?: string;
    "runtime": string;
    "state": string;
}

export interface UpdateInfo {
    "currentVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "releaseUrl": string;
    "downloadUrl": string;
    "releaseNotes": string;
    "publishedAt": string;
}

export interface UpdateProgress {
    "phase": string;
    "percent": number;
    "bytesReceived": number;
    "bytesTotal": number;
    "message": string;
    "error"?: string;
    "readyToRestart": boolean;
}

export interface UserSettings {
    "activeRuntime": string;
    "workspace": string;
    "recentWorkspaces": string[] | null;
    "grokWorkspace": string;
    "grokRecentWorkspaces": string[] | null;
    "grokBackend": string;
    "grokBuildModel": string;
    "grokAPIModel": string;
    "grokEffort": string;
    "grokSandbox": string;
    "grokApprovalPolicy": string;
    "grokWebSearch": boolean;
    "grokXSearch": boolean;

    /**
     * GrokAPIKey / GrokAPIBaseURL configure NiceCodex Grok API mode (OpenAI-compatible).
     * Empty key falls back to XAI_API_KEY / GROK_API_KEY env; empty base uses https://api.x.ai/v1.
     */
    "grokAPIKey": string;
    "grokAPIBaseURL": string;

    /**
     * Claude Code independent stack (workspace / model / permissions).
     */
    "claudeWorkspace": string;
    "claudeRecentWorkspaces": string[] | null;
    "claudeModel": string;
    "claudeEffort": string;
    "claudeSandbox": string;
    "claudeApprovalPolicy": string;

    /**
     * ClaudePermissionMode is the official Claude Code --permission-mode value when set:
     * acceptEdits | auto | bypassPermissions | manual | dontAsk | plan.
     * Empty falls back to ClaudeSandbox + ClaudeApprovalPolicy mapping.
     */
    "claudePermissionMode": string;

    /**
     * ClaudeCustomModels are free-form --model ids (aliases or full IDs) kept per-user.
     */
    "claudeCustomModels": string[] | null;

    /**
     * GrokCustomModels are free-form model ids for Build CLI / API mode pickers.
     */
    "grokCustomModels": string[] | null;

    /**
     * Gemini/OpenCode preferences stay separate from Codex/Claude/Grok so a
     * runtime switch never changes another provider's default model.
     */
    "geminiWorkspace": string;
    "geminiRecentWorkspaces": string[] | null;
    "geminiModel": string;
    "geminiEffort": string;
    "geminiSandbox": string;
    "geminiApprovalPolicy": string;
    "geminiCustomModels": string[] | null;
    "openCodeModel": string;
    "openCodeWorkspace": string;
    "openCodeRecentWorkspaces": string[] | null;
    "openCodeEffort": string;
    "openCodeSandbox": string;
    "openCodeApprovalPolicy": string;
    "openCodeProvider": string;
    "openCodeCustomModels": string[] | null;
    "model": string;
    "codexContextWindow": number;
    "codexAutoCompactThreshold": number;
    "modelProvider": string;
    "customModels": string[] | null;
    "effort": string;
    "serviceTier": string;
    "collaborationMode": string;
    "personality": string;
    "multiAgentMode": string;
    "sandbox": string;
    "approvalPolicy": string;
    "theme": string;
    "accentColor": string;
    "fontFamily": string;
    "terminalProfile": string;
    "language": string;
    "autoConnect": boolean;
    "workMode": string;
    "sendWithModifier": boolean;
    "followUpBehavior": string;
    "notifyOnTurnComplete": boolean;
    "customInstructions": string;
    "translucentSidebar": boolean;
    "highContrast": boolean;
    "pointerCursor": boolean;
    "reduceMotion": boolean;
    "uiFontSize": string;
    "codeFontSize": string;
    "preventSleepWhileRunning": boolean;
    "alwaysOnTop": boolean;
    "gitBranchPrefix": string;
    "gitCommitPrefix": string;
    "gitOpenPRAfterPush": boolean;
    "gitPRBodyTemplate": string;
    "browserAllowedHosts": string[] | null;
    "browserBlockedHosts": string[] | null;
    "browserDownloadDir": string;
    "browserFullCDP": boolean;
    "shortcutCommandPalette": string;
    "shortcutNewThread": string;
    "shortcutTerminal": string;
    "shortcutBrowser": string;

    /**
     * CodexClient* is the app-server initialize clientInfo sent upstream as User-Agent.
     * Empty values fall back to official Codex Desktop defaults (or NICE_CODEX_CLIENT_* env).
     */
    "codexClientName": string;
    "codexClientTitle": string;
    "codexClientVersion": string;

    /**
     * NetworkProxy* lets users point Codex / CLI traffic at Clash (or similar)
     * HTTP mixed ports without enabling TUN. Applied as process env + child inherit.
     */
    "networkProxyEnabled": boolean;
    "networkProxyUrl": string;
    "networkProxyNoProxy": string;
    "onboardingCompleted": boolean;
}

export interface WorkspaceInfo {
    "name": string;
    "path": string;
    "isGit": boolean;
    "branch": string;
    "changes": GitChange[] | null;
    "gitError"?: string;
}
