// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as codex$0 from "./internal/codex/models.js";

export interface AgentProviderModel {
    "model": string;
    "displayName": string;
    "description": string;
    "isDefault": boolean;
}

export interface AgentProviderReasoningEffort {
    "effort": string;
    "displayName": string;
    "description": string;
    "isDefault": boolean;
}

export interface AgentProviderRuntime {
    "id": string;
    "name": string;
    "kind": string;
    "installed": boolean;
    "healthy": boolean;
    "runtimeReady": boolean;
    "version": string;
    "executable": string;
    "status": string;
    "message": string;
    "capabilities": string[] | null;
    "models": AgentProviderModel[] | null;
    "reasoningEfforts": AgentProviderReasoningEffort[] | null;
}

export interface BootstrapData {
    "codex": codex$0.Detection;
    "agentProviders": AgentProviderRuntime[] | null;
    "settings": UserSettings;
    "workspace"?: WorkspaceInfo | null;
    "terminalProfiles": TerminalProfile[] | null;
    "appVersion": string;
    "updateRepo": string;
}

export interface GitChange {
    "status": string;
    "path": string;
}

export interface MCPServerWriteRequest {
    "name": string;
    "enabled": boolean;
    "command": string;
    "args": string[] | null;
    "url": string;
    "transport": string;
    "env": { [_ in string]?: string } | null;
}

export interface PluginInstallRequest {
    "pluginName": string;
    "marketplacePath": string;
    "remoteMarketplaceName": string;
}

/**
 * ProjectInstructionsInfo is the workspace-root AGENTS.md (project-scoped Codex guidance).
 */
export interface ProjectInstructionsInfo {
    "content": string;
    "workspace": string;
    "path": string;
    "available": boolean;
}

export interface ReviewStartRequest {
    "threadId": string;
    "targetType": string;
    "branch": string;
    "instructions": string;
    "delivery": string;
}

export interface SendMessageRequest {
    "threadId": string;
    "text": string;
    "images": string[] | null;

    /**
     * Per-turn mode override — mirrors official TUI SubmitUserMessageWithMode.
     */
    "collaborationMode"?: string;
}

export interface SessionPreferencesRequest {
    "sessionId": string;
    "model": string;
    "effort": string;
    "collaborationMode": string;
}

export interface SkillConfigRequest {
    "name": string;
    "path": string;
    "enabled": boolean;
}

export interface SteerTurnRequest {
    "threadId": string;
    "turnId": string;
    "text": string;
    "images": string[] | null;
}

export interface SystemFont {
    "family": string;
    "source": string;
}

export interface TerminalProfile {
    "id": string;
    "name": string;
    "description": string;
    "available": boolean;
}

export interface UpdateInfo {
    "currentVersion": string;
    "latestVersion": string;
    "updateAvailable": boolean;
    "releaseUrl": string;
    "downloadUrl": string;
    "releaseNotes": string;
    "publishedAt": string;
}

export interface UserSettings {
    "workspace": string;
    "recentWorkspaces": string[] | null;
    "model": string;
    "modelProvider": string;
    "customModels": string[] | null;
    "effort": string;
    "serviceTier": string;
    "collaborationMode": string;
    "personality": string;
    "multiAgentMode": string;
    "sandbox": string;
    "approvalPolicy": string;
    "theme": string;
    "accentColor": string;
    "fontFamily": string;
    "terminalProfile": string;
    "language": string;
    "autoConnect": boolean;
    "workMode": string;
    "sendWithModifier": boolean;
    "followUpBehavior": string;
    "notifyOnTurnComplete": boolean;
    "customInstructions": string;
}

export interface WorkspaceInfo {
    "name": string;
    "path": string;
    "isGit": boolean;
    "branch": string;
    "changes": GitChange[] | null;
    "gitError"?: string;
}
