// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as codex$0 from "../../../../../nice_codex_desktop/internal/codex/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "codex:event": codex$0.Event;
        }
    }
}
