/**
 * Claude Code backend calls.
 * Prefer generated ByID bindings first; fall back to Call.ByName when hashes drift.
 */
import { Call } from '@wailsio/runtime'

import * as backend from '../../bindings/nice_codex_desktop/appservice'

const SERVICE = 'nice_codex_desktop.AppService'

export interface ClaudeRuntimeStatus {
  available: boolean
  authenticated: boolean
  version: string
  executable: string
  message: string
}

export interface ClaudeSessionSummary {
  id: string
  workspace: string
  name: string
  preview: string
  model: string
  effort: string
  createdAt: number
  updatedAt: number
}

export interface ClaudeMessage {
  id: string
  role: string
  text: string
  toolName?: string
  status?: string
  createdAt: number
}

export interface ClaudeSessionDetail {
  summary: ClaudeSessionSummary
  messages: ClaudeMessage[] | null
}

export interface ClaudeSendRequest {
  sessionId: string
  workspace: string
  text: string
  images: string[]
  model: string
  effort: string
}

export interface ClaudeTurnRef {
  sessionId: string
  turnId: string
}

export interface ClaudeTurnUsageView {
  index: number
  turnId: string
  sessionId: string
  tokenUsage: {
    inputTokens: number
    cachedInputTokens: number
    outputTokens: number
    reasoningOutputTokens: number
    totalTokens: number
  }
  at?: number
}

export interface ClaudeMCPServerView {
  name: string
  enabled: boolean
  command: string
  args: string
  transport: string
  url: string
  scope: string
  source: string
}

export interface ClaudeSkillView {
  name: string
  displayName: string
  description: string
  path: string
  scope: string
}

export interface ClaudePluginView {
  name: string
  version: string
  scope: string
  path: string
}

export interface ClaudeAgentView {
  name: string
  displayName: string
  description: string
  path: string
  scope: string
}

export interface ClaudeCommandView {
  name: string
  path: string
  scope: string
}

export interface ClaudeHookView {
  event: string
  command: string
  source: string
}

export interface ClaudeSettingsSummary {
  path: string
  exists: boolean
  model: string
  permissionMode: string
  allowRules: number
  denyRules: number
  envKeys: string[] | null
  baseURL: string
  skipDangerPrompt: boolean
  hasStatusLine: boolean
  rawPermissionMode: string
}

export interface ClaudeCapabilitiesCatalog {
  runtime: ClaudeRuntimeStatus
  configPath: string
  claudeHome: string
  claudeJsonPath: string
  settings: ClaudeSettingsSummary
  mcp: ClaudeMCPServerView[] | null
  skills: ClaudeSkillView[] | null
  plugins: ClaudePluginView[] | null
  agents: ClaudeAgentView[] | null
  commands: ClaudeCommandView[] | null
  hooks: ClaudeHookView[] | null
  globalInstructions: {
    content: string
    path: string
    source: string
    exists: boolean
    emptyFile: boolean
    available: boolean
  }
  projectInstructions: {
    content: string
    workspace: string
    workspaceName: string
    path: string
    source: string
    exists: boolean
    emptyFile: boolean
    available: boolean
  }
}

function isBindingError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error || '')
  return /unknown bound method|binding call failed/i.test(message)
}

async function withNameFallback<T>(
  method: string,
  byId: () => Promise<T>,
  ...args: unknown[]
): Promise<T> {
  try {
    return await byId()
  } catch (error) {
    if (!isBindingError(error)) throw error
    return await Call.ByName(`${SERVICE}.${method}`, ...args) as T
  }
}

function byIdOrName<T>(method: string, fn: (() => Promise<T>) | undefined, ...args: unknown[]): Promise<T> {
  if (typeof fn === 'function') {
    return withNameFallback(method, fn, ...args)
  }
  return Call.ByName(`${SERVICE}.${method}`, ...args) as Promise<T>
}

export function refreshClaudeRuntime(): Promise<ClaudeRuntimeStatus> {
  return byIdOrName('RefreshClaudeRuntime', () => (backend as any).RefreshClaudeRuntime())
}

export function listClaudeSessions(workspace: string, search: string): Promise<ClaudeSessionSummary[] | null> {
  return byIdOrName(
    'ListClaudeSessions',
    () => (backend as any).ListClaudeSessions(workspace, search),
    workspace,
    search,
  )
}

export function listArchivedClaudeSessions(): Promise<ClaudeSessionSummary[] | null> {
  return byIdOrName('ListArchivedClaudeSessions', () => (backend as any).ListArchivedClaudeSessions())
}

export function readClaudeSession(sessionID: string): Promise<ClaudeSessionDetail> {
  return byIdOrName('ReadClaudeSession', () => (backend as any).ReadClaudeSession(sessionID), sessionID)
}

export function listClaudeSessionTurnUsages(sessionID: string): Promise<ClaudeTurnUsageView[] | null> {
  return byIdOrName(
    'ListClaudeSessionTurnUsages',
    () => (backend as any).ListClaudeSessionTurnUsages?.(sessionID),
    sessionID,
  )
}

export function sendClaudeMessage(request: ClaudeSendRequest): Promise<ClaudeTurnRef> {
  return byIdOrName('SendClaudeMessage', () => (backend as any).SendClaudeMessage(request), request)
}

export function interruptClaudeTurn(ref: ClaudeTurnRef): Promise<void> {
  return byIdOrName('InterruptClaudeTurn', () => (backend as any).InterruptClaudeTurn(ref), ref)
}

export function deleteClaudeSession(sessionID: string): Promise<void> {
  return byIdOrName('DeleteClaudeSession', () => (backend as any).DeleteClaudeSession(sessionID), sessionID)
}

export function renameClaudeSession(sessionID: string, name: string): Promise<void> {
  return byIdOrName('RenameClaudeSession', () => (backend as any).RenameClaudeSession(sessionID, name), sessionID, name)
}

export function archiveClaudeSession(sessionID: string): Promise<void> {
  return byIdOrName('ArchiveClaudeSession', () => (backend as any).ArchiveClaudeSession(sessionID), sessionID)
}

export function unarchiveClaudeSession(sessionID: string): Promise<void> {
  return byIdOrName('UnarchiveClaudeSession', () => (backend as any).UnarchiveClaudeSession(sessionID), sessionID)
}

export function selectClaudeWorkspace() {
  return byIdOrName('SelectClaudeWorkspace', () => (backend as any).SelectClaudeWorkspace())
}

export function useClaudeWorkspace(path: string) {
  return byIdOrName('UseClaudeWorkspace', () => (backend as any).UseClaudeWorkspace(path), path)
}

export function readClaudeCapabilities(): Promise<ClaudeCapabilitiesCatalog> {
  return byIdOrName('ReadClaudeCapabilities', () => (backend as any).ReadClaudeCapabilities())
}

export function readClaudeGlobalInstructions() {
  return byIdOrName('ReadClaudeGlobalInstructions', () => (backend as any).ReadClaudeGlobalInstructions())
}

export function saveClaudeGlobalInstructions(content: string) {
  return byIdOrName('SaveClaudeGlobalInstructions', () => (backend as any).SaveClaudeGlobalInstructions(content), content)
}

export function readClaudeProjectInstructions() {
  return byIdOrName('ReadClaudeProjectInstructions', () => (backend as any).ReadClaudeProjectInstructions())
}

export function saveClaudeProjectInstructions(content: string) {
  return byIdOrName('SaveClaudeProjectInstructions', () => (backend as any).SaveClaudeProjectInstructions(content), content)
}

export function openClaudeHome(): Promise<void> {
  return byIdOrName('OpenClaudeHome', () => (backend as any).OpenClaudeHome())
}

export function openClaudeConfigFile(): Promise<void> {
  return byIdOrName('OpenClaudeConfigFile', () => (backend as any).OpenClaudeConfigFile())
}
