/**
 * CLI install / update backend calls.
 * Prefer generated ByID bindings; fall back to Call.ByName when hashes are stale.
 */
import { Call } from '@wailsio/runtime'

import * as backend from '../../bindings/nice_codex_desktop/appservice'

const SERVICE = 'nice_codex_desktop.AppService'

export interface CLIToolStatus {
  id: string
  name: string
  package: string
  installCommand: string
  installed: boolean
  executable: string
  version: string
  latestVersion: string
  updateAvailable: boolean
  packageManager: string
  message: string
  canInstall: boolean
  nodeAvailable: boolean
}

export interface CLIToolsReport {
  tools: CLIToolStatus[] | null
  packageManager: string
  nodeAvailable: boolean
  nodeVersion: string
  checkedAt: number
  /** GOOS: windows | darwin | linux */
  platform?: string
  codexHome?: string
  grokHome?: string
}

export interface CLIToolActionResult {
  ok: boolean
  message: string
  output: string
  tool: CLIToolStatus
}

function isBindingError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error || '')
  return /unknown bound method|binding call failed/i.test(message)
}

async function withNameFallback<T>(
  method: string,
  byId: () => Promise<T>,
  ...args: unknown[]
): Promise<T> {
  try {
    return await byId()
  } catch (error) {
    if (!isBindingError(error)) throw error
    return await Call.ByName(`${SERVICE}.${method}`, ...args) as T
  }
}

export function checkCLITools(): Promise<CLIToolsReport> {
  return withNameFallback(
    'CheckCLITools',
    () => backend.CheckCLITools() as Promise<CLIToolsReport>,
  )
}

export function installCLITool(toolID: string): Promise<CLIToolActionResult> {
  return withNameFallback(
    'InstallCLITool',
    () => backend.InstallCLITool(toolID) as Promise<CLIToolActionResult>,
    toolID,
  )
}
