// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Detection {
    "available": boolean;
    "binary": string;
    "version": string;
    "error"?: string;
}

export interface Event {
    "type": string;
    "method"?: string;
    "requestKey"?: string;
    "data"?: any;
}

export interface Status {
    "state": string;
    "running": boolean;
    "message": string;
    "binary": string;
    "version": string;
    "workspace": string;
}
